services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=gemini-backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: gemini-ai-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db:5432/gemini-ai-backend-system?schema=public"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_GENAI_API_KEY: ${GOOGLE_GENAI_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PRO_PRICE_ID: ${STRIPE_PRO_PRICE_ID}
      FRONTEND_URL: ${FRONTEND_URL}

volumes:
  postgres_data:
  redis_data:
