services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gemini-backend
    ports:
      - "5431:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"